(deftheme CondorEmacs
  "Official theme.")

(custom-theme-set-variables
 'CondorEmacs
 '(ansi-color-names-vector ["#272822" "#F92672" "#A6E22E" "#E6DB74" "#66D9EF" "#FD5FF0" "#A1EFE4" "#F8F8F2"])
 '(compilation-message-face (quote default)))

(custom-theme-set-faces
 'CondorEmacs
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(font-lock-keyword-face ((t (:foreground "#66D9EF" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((t (:foreground "#66D9EF" :slant normal))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(c-annotation-face ((((class color) (min-colors 257)) (:inherit font-lock-constant-face)) (((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(button ((t (:underline t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#49483E")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:inherit highlight :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit highlight :background "#3E3E3E"))))
 '(region ((((class color) (min-colors 257)) (:inherit highlight :background "#49483E")) (((class color) (min-colors 89)) (:inherit highlight :background "#474747"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:inherit region :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit region :background "#3E3E3E"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#272822" :weight bold)) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#AE81FF" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#F92672")) (((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#64645E")) (((class color) (min-colors 89)) (:foreground "#3D3D3D"))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F0" :background "#49483E" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#1B1E1C" :box (:line-width 1 :color "#474747" :style unspecified)))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#75715E" :background "#272822" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#3D3D3D" :style unspecified)))))
 '(header-line ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#49483E" :box (:color "#64645E" :line-width 1 :style unspecified))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#474747" :box (:color "#3D3D3D" :line-width 1 :style unspecified)))))
 '(isearch ((((class color) (min-colors 257)) (:inherit region :foreground "#272822" :background "#E6DB74")) (((class color) (min-colors 89)) (:inherit region :foreground "#1B1E1C" :background "#CDC673"))))
 '(isearch-fail ((((class color) (min-colors 257)) (:inherit isearch :foreground "#F92672" :background "#272822" :bold t)) (((class color) (min-colors 89)) (:inherit isearch :foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(company-tooltip ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-tooltip-selection ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(company-tooltip-common ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(company-tooltip-common-selection ((((class color) (min-colors 257)) (:foreground "#272822" :background "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF" :underline t))))
 '(company-preview ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(company-scrollbar-bg ((((class color) (min-colors 257)) (:background "#64645E")) (((class color) (min-colors 89)) (:background "#3D3D3D"))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#75715E")) (((class color) (min-colors 89)) (:background "#8B8878"))))
 '(company-tooltip-annotation ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#A6E22E")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#87D700"))))
 '(company-template-field ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#66D9EF")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#5FD7FF"))))
 '(compilation-column-number ((((class color) (min-colors 257)) (:inherit font-lock-doc-face :foreground "#A1EFE4" :underline nil)) (((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#5FFFFF" :underline nil))))
 '(compilation-error ((((class color) (min-colors 257)) (:inherit error :underline nil)) (((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 257)) (:foreground "#75715E" :underline nil :bold nil)) (((class color) (min-colors 89)) (:foreground "#8B8878" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#A6E22E" :underline nil)) (((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 257)) (:inherit warning :underline nil)) (((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 257)) (:inherit compilation-info :foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-info :foreground "#87D700" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 257)) (:inherit compilation-error :foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-error :foreground "#FF1493" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit default :height 1.2 :foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:inherit default :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#A1EFE4" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit default :foreground "#F92672" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(flymake-error ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#F92672") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 257)) (:foreground "#FEB0CC" :background "#F20055" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#870000" :background "#FF5F87" :weight bold :underline t))))
 '(flymake-warning ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#E6DB74") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 257)) (:foreground "#FFFACE" :background "#9A8F21" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#878700" :background "#FFFF87" :weight bold :underline t))))
 '(info-header-xref ((((class color) (min-colors 257)) (:foreground "#A6E22E" :inherit bold :underline t)) (((class color) (min-colors 89)) (:foreground "#87D700" :inherit bold :underline t))))
 '(info-node ((((class color) (min-colors 257)) (:foreground "#AE81FF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 257)) (:height 1.3)) (((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-2 ((((class color) (min-colors 257)) (:height 1.2)) (((class color) (min-colors 89)) (:height 1.2))))
 '(info-title-3 ((((class color) (min-colors 257)) (:height 1.15)) (((class color) (min-colors 89)) (:height 1.15))))
 '(info-title-4 ((((class color) (min-colors 257)) (:height 1.1)) (((class color) (min-colors 89)) (:height 1.1))))
 '(linum ((((class color) (min-colors 257)) (:foreground "#8F908A" :background "#272822" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#8F908A" :background "#1B1E1C" :inherit default :underline nil))))
 '(line-number ((((class color) (min-colors 257)) (:foreground "#8F908A" :background "#272822" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#8F908A" :background "#1B1E1C" :inherit default :underline nil))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C" :inherit default :underline nil))))
 '(markdown-header-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(markdown-header-face-1 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.3)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-2 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.2)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.2))))
 '(markdown-header-face-3 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.15)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.15))))
 '(markdown-header-face-4 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.1)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.1))))
 '(markdown-header-face-5 ((((class color) (min-colors 257)) (:inherit markdown-header-face)) (((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-6 ((((class color) (min-colors 257)) (:inherit markdown-header-face)) (((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(outline-1 ((((class color) (min-colors 257)) (:inherit org-level-1)) (((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 257)) (:inherit org-level-2)) (((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 257)) (:inherit org-level-3)) (((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 257)) (:inherit org-level-4)) (((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 257)) (:inherit org-level-5)) (((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 257)) (:inherit org-level-6)) (((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 257)) (:inherit org-level-7)) (((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 257)) (:inherit org-level-8)) (((class color) (min-colors 89)) (:inherit org-level-8))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#FFFACE" :foreground "#272822" :inherit default))))
 '(whitespace-space ((((class color) (min-colors 257)) (:background unspecified :foreground "#75715E" :inverse-video unspecified :slant italic)) (((class color) (min-colors 89)) (:background unspecified :foreground "#8B8878" :inverse-video unspecified :slant italic))))
 '(whitespace-hspace ((((class color) (min-colors 257)) (:background unspecified :foreground "#F8F8F0" :inverse-video unspecified)) (((class color) (min-colors 89)) (:background unspecified :foreground "#FFFAFA" :inverse-video unspecified))))
 '(whitespace-tab ((((class color) (min-colors 257)) (:background unspecified :foreground "#F92672" :inverse-video unspecified :weight bold)) (((class color) (min-colors 89)) (:background unspecified :foreground "#FF1493" :inverse-video unspecified :weight bold))))
 '(whitespace-newline ((((class color) (min-colors 257)) (:background unspecified :foreground "#75715E" :inverse-video unspecified)) (((class color) (min-colors 89)) (:background unspecified :foreground "#8B8878" :inverse-video unspecified))))
 '(whitespace-trailing ((((class color) (min-colors 257)) (:background unspecified :foreground "#A75B00" :inverse-video t)) (((class color) (min-colors 89)) (:background unspecified :foreground "#FFAF5F" :inverse-video t))))
 '(whitespace-line ((((class color) (min-colors 257)) (:background unspecified :foreground "#FD5FF0" :inverse-video unspecified)) (((class color) (min-colors 89)) (:background unspecified :foreground "#D700D7" :inverse-video unspecified))))
 '(whitespace-space-before-tab ((((class color) (min-colors 257)) (:background "#F20055" :foreground unspecified :inverse-video unspecified)) (((class color) (min-colors 89)) (:background "#FF5F87" :foreground unspecified :inverse-video unspecified))))
 '(whitespace-indentation ((((class color) (min-colors 257)) (:background unspecified :foreground "#E6DB74" :inverse-video unspecified :weight bold)) (((class color) (min-colors 89)) (:background unspecified :foreground "#CDC673" :inverse-video unspecified :weight bold))))
 '(whitespace-empty ((((class color) (min-colors 257)) (:background unspecified :foreground "#F20055" :inverse-video t)) (((class color) (min-colors 89)) (:background unspecified :foreground "#FF5F87" :inverse-video t))))
 '(whitespace-space-after-tab ((((class color) (min-colors 257)) (:background unspecified :foreground "#FD971F" :inverse-video t :weight bold)) (((class color) (min-colors 89)) (:background unspecified :foreground "#FF8C00" :inverse-video t :weight bold))))
 '(default ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C")))))

(provide-theme 'CondorEmacs)
